//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace WDAIIP.WEB.ITSWebc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="twsITSWebcSoap", Namespace="https://itsapi.etraining.gov.tw/ITSWebExport/")]
    public partial class twsITSWebc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStudHis1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudHis2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public twsITSWebc() {
            this.Url = global::WDAIIP.WEB.Properties.Settings.Default.WDAIIP_WEB_ITSWebc_twsITSWebc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStudHis1CompletedEventHandler GetStudHis1Completed;
        
        /// <remarks/>
        public event GetStudHis2CompletedEventHandler GetStudHis2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://itsapi.etraining.gov.tw/ITSWebExport/GetStudHis1", RequestNamespace="https://itsapi.etraining.gov.tw/ITSWebExport/", ResponseNamespace="https://itsapi.etraining.gov.tw/ITSWebExport/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultOfSTUDENT_TRAINING_HISTORY_VIEW GetStudHis1(string s_AUTH, string s_IDNO, string s_BIRTHDAY) {
            object[] results = this.Invoke("GetStudHis1", new object[] {
                        s_AUTH,
                        s_IDNO,
                        s_BIRTHDAY});
            return ((ResultOfSTUDENT_TRAINING_HISTORY_VIEW)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudHis1Async(string s_AUTH, string s_IDNO, string s_BIRTHDAY) {
            this.GetStudHis1Async(s_AUTH, s_IDNO, s_BIRTHDAY, null);
        }
        
        /// <remarks/>
        public void GetStudHis1Async(string s_AUTH, string s_IDNO, string s_BIRTHDAY, object userState) {
            if ((this.GetStudHis1OperationCompleted == null)) {
                this.GetStudHis1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudHis1OperationCompleted);
            }
            this.InvokeAsync("GetStudHis1", new object[] {
                        s_AUTH,
                        s_IDNO,
                        s_BIRTHDAY}, this.GetStudHis1OperationCompleted, userState);
        }
        
        private void OnGetStudHis1OperationCompleted(object arg) {
            if ((this.GetStudHis1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudHis1Completed(this, new GetStudHis1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://itsapi.etraining.gov.tw/ITSWebExport/GetStudHis2", RequestNamespace="https://itsapi.etraining.gov.tw/ITSWebExport/", ResponseNamespace="https://itsapi.etraining.gov.tw/ITSWebExport/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultOfSTUDENT_TRAINING_HISTORY_VIEW GetStudHis2(string s_AUTH, string s_IDNOs) {
            object[] results = this.Invoke("GetStudHis2", new object[] {
                        s_AUTH,
                        s_IDNOs});
            return ((ResultOfSTUDENT_TRAINING_HISTORY_VIEW)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudHis2Async(string s_AUTH, string s_IDNOs) {
            this.GetStudHis2Async(s_AUTH, s_IDNOs, null);
        }
        
        /// <remarks/>
        public void GetStudHis2Async(string s_AUTH, string s_IDNOs, object userState) {
            if ((this.GetStudHis2OperationCompleted == null)) {
                this.GetStudHis2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudHis2OperationCompleted);
            }
            this.InvokeAsync("GetStudHis2", new object[] {
                        s_AUTH,
                        s_IDNOs}, this.GetStudHis2OperationCompleted, userState);
        }
        
        private void OnGetStudHis2OperationCompleted(object arg) {
            if ((this.GetStudHis2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudHis2Completed(this, new GetStudHis2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://itsapi.etraining.gov.tw/ITSWebExport/")]
    public partial class ResultOfSTUDENT_TRAINING_HISTORY_VIEW {
        
        private string responseField;
        
        private string codeField;
        
        private string errMsgField;
        
        private int countField;
        
        private string hashCodeField;
        
        private STUDENT_TRAINING_HISTORY_VIEW[] recordsField;
        
        /// <remarks/>
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string HashCode {
            get {
                return this.hashCodeField;
            }
            set {
                this.hashCodeField = value;
            }
        }
        
        /// <remarks/>
        public STUDENT_TRAINING_HISTORY_VIEW[] Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://itsapi.etraining.gov.tw/ITSWebExport/")]
    public partial class STUDENT_TRAINING_HISTORY_VIEW {
        
        private string hashCodeField;
        
        private string tPLANIDField;
        
        private int oCIDField;
        
        private int tWYEARField;
        
        private string dISTIDField;
        
        private string dISTNAMEField;
        
        private int nTPSNOField;
        
        private string nTPNAMEField;
        
        private int bCM_SNOField;
        
        private string cLASSNAMEField;
        
        private string cYCLTYPEField;
        
        private string bNAField;
        
        private string bTINAMEField;
        
        private string uP_GOV_BTINAMEField;
        
        private System.DateTime cDI_BEGIN_DATEField;
        
        private System.DateTime cDI_END_DATEField;
        
        private int tHOURSField;
        
        private string tPERIODField;
        
        private string hOURRANNAMEField;
        
        private int tRAINHOURSField;
        
        private int cTTNOField;
        
        private string tRAINNAMEField;
        
        private string cGJTNOField;
        
        private string cGJT_NAMEField;
        
        private int sCDNOField;
        
        private int sOCIDField;
        
        private string iDNOField;
        
        private string iSDuplicateField;
        
        private string cNAMEField;
        
        private string eNAMEField;
        
        private string gENDERField;
        
        private System.DateTime bIRTHDAYField;
        
        private int cSSNOField;
        
        private string cSS_STATUSField;
        
        private string wORKSUPPIDENTField;
        
        private string wORKSUPPIDENT_NAMEField;
        
        private string rEJECTDAYIN14Field;
        
        private int cJCNOField;
        
        private int jOBSTATEField;
        
        private string cGTIDField;
        
        private string cGTNAMEField;
        
        private System.Nullable<decimal> sUMOFMONEYField;
        
        private string cBTIDField;
        
        private string cBTNAMEField;
        
        private string aPPLIEDSTATUSMField;
        
        private string aPPLIEDSTATUSM_NAMEField;
        
        private string aPPLIEDSTATUSField;
        
        private string aPPLIEDSTATUS_NAMEField;
        
        private string aPPLIEDNOTEField;
        
        private System.Nullable<System.DateTime> aLLOTDATEField;
        
        private System.Nullable<System.DateTime> eXIT_DATEField;
        
        /// <remarks/>
        public string HashCode {
            get {
                return this.hashCodeField;
            }
            set {
                this.hashCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TPLANID {
            get {
                return this.tPLANIDField;
            }
            set {
                this.tPLANIDField = value;
            }
        }
        
        /// <remarks/>
        public int OCID {
            get {
                return this.oCIDField;
            }
            set {
                this.oCIDField = value;
            }
        }
        
        /// <remarks/>
        public int TWYEAR {
            get {
                return this.tWYEARField;
            }
            set {
                this.tWYEARField = value;
            }
        }
        
        /// <remarks/>
        public string DISTID {
            get {
                return this.dISTIDField;
            }
            set {
                this.dISTIDField = value;
            }
        }
        
        /// <remarks/>
        public string DISTNAME {
            get {
                return this.dISTNAMEField;
            }
            set {
                this.dISTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int NTPSNO {
            get {
                return this.nTPSNOField;
            }
            set {
                this.nTPSNOField = value;
            }
        }
        
        /// <remarks/>
        public string NTPNAME {
            get {
                return this.nTPNAMEField;
            }
            set {
                this.nTPNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int BCM_SNO {
            get {
                return this.bCM_SNOField;
            }
            set {
                this.bCM_SNOField = value;
            }
        }
        
        /// <remarks/>
        public string CLASSNAME {
            get {
                return this.cLASSNAMEField;
            }
            set {
                this.cLASSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CYCLTYPE {
            get {
                return this.cYCLTYPEField;
            }
            set {
                this.cYCLTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string BNA {
            get {
                return this.bNAField;
            }
            set {
                this.bNAField = value;
            }
        }
        
        /// <remarks/>
        public string BTINAME {
            get {
                return this.bTINAMEField;
            }
            set {
                this.bTINAMEField = value;
            }
        }
        
        /// <remarks/>
        public string UP_GOV_BTINAME {
            get {
                return this.uP_GOV_BTINAMEField;
            }
            set {
                this.uP_GOV_BTINAMEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CDI_BEGIN_DATE {
            get {
                return this.cDI_BEGIN_DATEField;
            }
            set {
                this.cDI_BEGIN_DATEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CDI_END_DATE {
            get {
                return this.cDI_END_DATEField;
            }
            set {
                this.cDI_END_DATEField = value;
            }
        }
        
        /// <remarks/>
        public int THOURS {
            get {
                return this.tHOURSField;
            }
            set {
                this.tHOURSField = value;
            }
        }
        
        /// <remarks/>
        public string TPERIOD {
            get {
                return this.tPERIODField;
            }
            set {
                this.tPERIODField = value;
            }
        }
        
        /// <remarks/>
        public string HOURRANNAME {
            get {
                return this.hOURRANNAMEField;
            }
            set {
                this.hOURRANNAMEField = value;
            }
        }
        
        /// <remarks/>
        public int TRAINHOURS {
            get {
                return this.tRAINHOURSField;
            }
            set {
                this.tRAINHOURSField = value;
            }
        }
        
        /// <remarks/>
        public int CTTNO {
            get {
                return this.cTTNOField;
            }
            set {
                this.cTTNOField = value;
            }
        }
        
        /// <remarks/>
        public string TRAINNAME {
            get {
                return this.tRAINNAMEField;
            }
            set {
                this.tRAINNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CGJTNO {
            get {
                return this.cGJTNOField;
            }
            set {
                this.cGJTNOField = value;
            }
        }
        
        /// <remarks/>
        public string CGJT_NAME {
            get {
                return this.cGJT_NAMEField;
            }
            set {
                this.cGJT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public int SCDNO {
            get {
                return this.sCDNOField;
            }
            set {
                this.sCDNOField = value;
            }
        }
        
        /// <remarks/>
        public int SOCID {
            get {
                return this.sOCIDField;
            }
            set {
                this.sOCIDField = value;
            }
        }
        
        /// <remarks/>
        public string IDNO {
            get {
                return this.iDNOField;
            }
            set {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        public string ISDuplicate {
            get {
                return this.iSDuplicateField;
            }
            set {
                this.iSDuplicateField = value;
            }
        }
        
        /// <remarks/>
        public string CNAME {
            get {
                return this.cNAMEField;
            }
            set {
                this.cNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ENAME {
            get {
                return this.eNAMEField;
            }
            set {
                this.eNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENDER {
            get {
                return this.gENDERField;
            }
            set {
                this.gENDERField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BIRTHDAY {
            get {
                return this.bIRTHDAYField;
            }
            set {
                this.bIRTHDAYField = value;
            }
        }
        
        /// <remarks/>
        public int CSSNO {
            get {
                return this.cSSNOField;
            }
            set {
                this.cSSNOField = value;
            }
        }
        
        /// <remarks/>
        public string CSS_STATUS {
            get {
                return this.cSS_STATUSField;
            }
            set {
                this.cSS_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public string WORKSUPPIDENT {
            get {
                return this.wORKSUPPIDENTField;
            }
            set {
                this.wORKSUPPIDENTField = value;
            }
        }
        
        /// <remarks/>
        public string WORKSUPPIDENT_NAME {
            get {
                return this.wORKSUPPIDENT_NAMEField;
            }
            set {
                this.wORKSUPPIDENT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string REJECTDAYIN14 {
            get {
                return this.rEJECTDAYIN14Field;
            }
            set {
                this.rEJECTDAYIN14Field = value;
            }
        }
        
        /// <remarks/>
        public int CJCNO {
            get {
                return this.cJCNOField;
            }
            set {
                this.cJCNOField = value;
            }
        }
        
        /// <remarks/>
        public int JOBSTATE {
            get {
                return this.jOBSTATEField;
            }
            set {
                this.jOBSTATEField = value;
            }
        }
        
        /// <remarks/>
        public string CGTID {
            get {
                return this.cGTIDField;
            }
            set {
                this.cGTIDField = value;
            }
        }
        
        /// <remarks/>
        public string CGTNAME {
            get {
                return this.cGTNAMEField;
            }
            set {
                this.cGTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SUMOFMONEY {
            get {
                return this.sUMOFMONEYField;
            }
            set {
                this.sUMOFMONEYField = value;
            }
        }
        
        /// <remarks/>
        public string CBTID {
            get {
                return this.cBTIDField;
            }
            set {
                this.cBTIDField = value;
            }
        }
        
        /// <remarks/>
        public string CBTNAME {
            get {
                return this.cBTNAMEField;
            }
            set {
                this.cBTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string APPLIEDSTATUSM {
            get {
                return this.aPPLIEDSTATUSMField;
            }
            set {
                this.aPPLIEDSTATUSMField = value;
            }
        }
        
        /// <remarks/>
        public string APPLIEDSTATUSM_NAME {
            get {
                return this.aPPLIEDSTATUSM_NAMEField;
            }
            set {
                this.aPPLIEDSTATUSM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string APPLIEDSTATUS {
            get {
                return this.aPPLIEDSTATUSField;
            }
            set {
                this.aPPLIEDSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string APPLIEDSTATUS_NAME {
            get {
                return this.aPPLIEDSTATUS_NAMEField;
            }
            set {
                this.aPPLIEDSTATUS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string APPLIEDNOTE {
            get {
                return this.aPPLIEDNOTEField;
            }
            set {
                this.aPPLIEDNOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ALLOTDATE {
            get {
                return this.aLLOTDATEField;
            }
            set {
                this.aLLOTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EXIT_DATE {
            get {
                return this.eXIT_DATEField;
            }
            set {
                this.eXIT_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetStudHis1CompletedEventHandler(object sender, GetStudHis1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudHis1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudHis1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultOfSTUDENT_TRAINING_HISTORY_VIEW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultOfSTUDENT_TRAINING_HISTORY_VIEW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetStudHis2CompletedEventHandler(object sender, GetStudHis2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudHis2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudHis2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultOfSTUDENT_TRAINING_HISTORY_VIEW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultOfSTUDENT_TRAINING_HISTORY_VIEW)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591