//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace WDAIIP.WEB.ojt0219ws1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetOjt0219ws1Soap", Namespace="http://ojt/OJTWS/GetOjt0219ws1")]
    public partial class GetOjt0219ws1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataS3OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRemSubCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSumOfMoneyCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTotalSubCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLabCostDayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetOjt0219ws1() {
            this.Url = global::WDAIIP.WEB.Properties.Settings.Default.WDAIIP_WEB_ojt0219ws1_GetOjt0219ws1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataS3CompletedEventHandler GetDataS3Completed;
        
        /// <remarks/>
        public event GetRemSubCostCompletedEventHandler GetRemSubCostCompleted;
        
        /// <remarks/>
        public event GetSumOfMoneyCostCompletedEventHandler GetSumOfMoneyCostCompleted;
        
        /// <remarks/>
        public event GetTotalSubCostCompletedEventHandler GetTotalSubCostCompleted;
        
        /// <remarks/>
        public event GetLabCostDayCompletedEventHandler GetLabCostDayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ojt/OJTWS/GetOjt0219ws1/GetDataS3", RequestNamespace="http://ojt/OJTWS/GetOjt0219ws1", ResponseNamespace="http://ojt/OJTWS/GetOjt0219ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDataS3(string aIDNO) {
            object[] results = this.Invoke("GetDataS3", new object[] {
                        aIDNO});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataS3Async(string aIDNO) {
            this.GetDataS3Async(aIDNO, null);
        }
        
        /// <remarks/>
        public void GetDataS3Async(string aIDNO, object userState) {
            if ((this.GetDataS3OperationCompleted == null)) {
                this.GetDataS3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataS3OperationCompleted);
            }
            this.InvokeAsync("GetDataS3", new object[] {
                        aIDNO}, this.GetDataS3OperationCompleted, userState);
        }
        
        private void OnGetDataS3OperationCompleted(object arg) {
            if ((this.GetDataS3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataS3Completed(this, new GetDataS3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ojt/OJTWS/GetOjt0219ws1/GetRemSubCost", RequestNamespace="http://ojt/OJTWS/GetOjt0219ws1", ResponseNamespace="http://ojt/OJTWS/GetOjt0219ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetRemSubCost(string aIDNO, string STDATE1) {
            object[] results = this.Invoke("GetRemSubCost", new object[] {
                        aIDNO,
                        STDATE1});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetRemSubCostAsync(string aIDNO, string STDATE1) {
            this.GetRemSubCostAsync(aIDNO, STDATE1, null);
        }
        
        /// <remarks/>
        public void GetRemSubCostAsync(string aIDNO, string STDATE1, object userState) {
            if ((this.GetRemSubCostOperationCompleted == null)) {
                this.GetRemSubCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRemSubCostOperationCompleted);
            }
            this.InvokeAsync("GetRemSubCost", new object[] {
                        aIDNO,
                        STDATE1}, this.GetRemSubCostOperationCompleted, userState);
        }
        
        private void OnGetRemSubCostOperationCompleted(object arg) {
            if ((this.GetRemSubCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRemSubCostCompleted(this, new GetRemSubCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ojt/OJTWS/GetOjt0219ws1/GetSumOfMoneyCost", RequestNamespace="http://ojt/OJTWS/GetOjt0219ws1", ResponseNamespace="http://ojt/OJTWS/GetOjt0219ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetSumOfMoneyCost(string aIDNO, string STDATE1) {
            object[] results = this.Invoke("GetSumOfMoneyCost", new object[] {
                        aIDNO,
                        STDATE1});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetSumOfMoneyCostAsync(string aIDNO, string STDATE1) {
            this.GetSumOfMoneyCostAsync(aIDNO, STDATE1, null);
        }
        
        /// <remarks/>
        public void GetSumOfMoneyCostAsync(string aIDNO, string STDATE1, object userState) {
            if ((this.GetSumOfMoneyCostOperationCompleted == null)) {
                this.GetSumOfMoneyCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSumOfMoneyCostOperationCompleted);
            }
            this.InvokeAsync("GetSumOfMoneyCost", new object[] {
                        aIDNO,
                        STDATE1}, this.GetSumOfMoneyCostOperationCompleted, userState);
        }
        
        private void OnGetSumOfMoneyCostOperationCompleted(object arg) {
            if ((this.GetSumOfMoneyCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSumOfMoneyCostCompleted(this, new GetSumOfMoneyCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ojt/OJTWS/GetOjt0219ws1/GetTotalSubCost", RequestNamespace="http://ojt/OJTWS/GetOjt0219ws1", ResponseNamespace="http://ojt/OJTWS/GetOjt0219ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetTotalSubCost(string aIDNO, string STDATE1) {
            object[] results = this.Invoke("GetTotalSubCost", new object[] {
                        aIDNO,
                        STDATE1});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetTotalSubCostAsync(string aIDNO, string STDATE1) {
            this.GetTotalSubCostAsync(aIDNO, STDATE1, null);
        }
        
        /// <remarks/>
        public void GetTotalSubCostAsync(string aIDNO, string STDATE1, object userState) {
            if ((this.GetTotalSubCostOperationCompleted == null)) {
                this.GetTotalSubCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalSubCostOperationCompleted);
            }
            this.InvokeAsync("GetTotalSubCost", new object[] {
                        aIDNO,
                        STDATE1}, this.GetTotalSubCostOperationCompleted, userState);
        }
        
        private void OnGetTotalSubCostOperationCompleted(object arg) {
            if ((this.GetTotalSubCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTotalSubCostCompleted(this, new GetTotalSubCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ojt/OJTWS/GetOjt0219ws1/GetLabCostDay", RequestNamespace="http://ojt/OJTWS/GetOjt0219ws1", ResponseNamespace="http://ojt/OJTWS/GetOjt0219ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLabCostDay(string aIDNO, string STDATE1, string MSGTITLE1) {
            object[] results = this.Invoke("GetLabCostDay", new object[] {
                        aIDNO,
                        STDATE1,
                        MSGTITLE1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLabCostDayAsync(string aIDNO, string STDATE1, string MSGTITLE1) {
            this.GetLabCostDayAsync(aIDNO, STDATE1, MSGTITLE1, null);
        }
        
        /// <remarks/>
        public void GetLabCostDayAsync(string aIDNO, string STDATE1, string MSGTITLE1, object userState) {
            if ((this.GetLabCostDayOperationCompleted == null)) {
                this.GetLabCostDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLabCostDayOperationCompleted);
            }
            this.InvokeAsync("GetLabCostDay", new object[] {
                        aIDNO,
                        STDATE1,
                        MSGTITLE1}, this.GetLabCostDayOperationCompleted, userState);
        }
        
        private void OnGetLabCostDayOperationCompleted(object arg) {
            if ((this.GetLabCostDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLabCostDayCompleted(this, new GetLabCostDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetDataS3CompletedEventHandler(object sender, GetDataS3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataS3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataS3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetRemSubCostCompletedEventHandler(object sender, GetRemSubCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRemSubCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRemSubCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetSumOfMoneyCostCompletedEventHandler(object sender, GetSumOfMoneyCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSumOfMoneyCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSumOfMoneyCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetTotalSubCostCompletedEventHandler(object sender, GetTotalSubCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTotalSubCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTotalSubCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLabCostDayCompletedEventHandler(object sender, GetLabCostDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLabCostDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLabCostDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591