//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace WDAIIP.WEB.SendMailws3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://wdaiip/GetJobMail3")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMailTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WDAIIP.WEB.Properties.Settings.Default.WDAIIP_WEB_SendMailws3_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMailTCompletedEventHandler SendMailTCompleted;
        
        /// <remarks/>
        public event SendMailSCompletedEventHandler SendMailSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wdaiip/GetJobMail3/SendMailT", RequestNamespace="http://wdaiip/GetJobMail3", ResponseNamespace="http://wdaiip/GetJobMail3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMailT(string strFromName, string strFromEMail, string strToAddressName, string strToAddressEMail, string strSubject, string myHtmlBody, string strMailServer) {
            object[] results = this.Invoke("SendMailT", new object[] {
                        strFromName,
                        strFromEMail,
                        strToAddressName,
                        strToAddressEMail,
                        strSubject,
                        myHtmlBody,
                        strMailServer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailTAsync(string strFromName, string strFromEMail, string strToAddressName, string strToAddressEMail, string strSubject, string myHtmlBody, string strMailServer) {
            this.SendMailTAsync(strFromName, strFromEMail, strToAddressName, strToAddressEMail, strSubject, myHtmlBody, strMailServer, null);
        }
        
        /// <remarks/>
        public void SendMailTAsync(string strFromName, string strFromEMail, string strToAddressName, string strToAddressEMail, string strSubject, string myHtmlBody, string strMailServer, object userState) {
            if ((this.SendMailTOperationCompleted == null)) {
                this.SendMailTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailTOperationCompleted);
            }
            this.InvokeAsync("SendMailT", new object[] {
                        strFromName,
                        strFromEMail,
                        strToAddressName,
                        strToAddressEMail,
                        strSubject,
                        myHtmlBody,
                        strMailServer}, this.SendMailTOperationCompleted, userState);
        }
        
        private void OnSendMailTOperationCompleted(object arg) {
            if ((this.SendMailTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailTCompleted(this, new SendMailTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wdaiip/GetJobMail3/SendMailS", RequestNamespace="http://wdaiip/GetJobMail3", ResponseNamespace="http://wdaiip/GetJobMail3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMailS(string strFromName, string strFromEMail, string strToAddress, string strSubject, string myHtmlBody, string strMailServer) {
            object[] results = this.Invoke("SendMailS", new object[] {
                        strFromName,
                        strFromEMail,
                        strToAddress,
                        strSubject,
                        myHtmlBody,
                        strMailServer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailSAsync(string strFromName, string strFromEMail, string strToAddress, string strSubject, string myHtmlBody, string strMailServer) {
            this.SendMailSAsync(strFromName, strFromEMail, strToAddress, strSubject, myHtmlBody, strMailServer, null);
        }
        
        /// <remarks/>
        public void SendMailSAsync(string strFromName, string strFromEMail, string strToAddress, string strSubject, string myHtmlBody, string strMailServer, object userState) {
            if ((this.SendMailSOperationCompleted == null)) {
                this.SendMailSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailSOperationCompleted);
            }
            this.InvokeAsync("SendMailS", new object[] {
                        strFromName,
                        strFromEMail,
                        strToAddress,
                        strSubject,
                        myHtmlBody,
                        strMailServer}, this.SendMailSOperationCompleted, userState);
        }
        
        private void OnSendMailSOperationCompleted(object arg) {
            if ((this.SendMailSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailSCompleted(this, new SendMailSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendMailTCompletedEventHandler(object sender, SendMailTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendMailSCompletedEventHandler(object sender, SendMailSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591